/**
 * ReportController
 *
 * @description :: Server-side logic for managing Reports
 * @help        :: See http://sailsjs.org/#!/documentation/concepts/Controllers
 */

module.exports = {
	
	//function to get dashbord data
	aggregates: function(req, res) {
		var releases = null;
		var pieCharts = [];
		var passCount
		//get all releases
		Release.getReleases(function(results) {releases = results});

		_(releases).forEach(function(release) {
			var passCount = 0;
			var failCount = 0;
			var skipCount = 0;
			var unknownCount = 0;
			var reports = null;
			Reports.find({autoGenerated: true, release: release.id}).exec(function(err,result) {
				if(err) console.log(err);
				else{
					reports = result;
				};
			});
			_(reports).forEach(function(report){
				passCount += report.passTests;
				failCount += report.failTests;
				skipCount += report.skipTests;
				unknownCount += report.unknownTests;
			});
			var pieChartData = {
				{name : 'pass',
				count: passCount},
				{name : 'fail',
				count: failCount},
				{name : 'skip',
				count: skipCount},
				{name : 'unknown',
				count: unknownCount}
			};
			var piechart = {
				name : release.name,
				data : pieChartData
			};
		};

		//return json output
		view();


        var view = function() {
            var out = {
                releases: releases,
                pieCharts: pieCharts
            };
            
            res.json(out);
        }

	}
};

