/**
 * ReportController
 *
 * @description :: Server-side logic for managing Reports
 * @help        :: See http://sailsjs.org/#!/documentation/concepts/Controllers
 */

var DbGetterController = require('./DbGetterController');

module.exports = {
	
	//function to get dashbord data
	aggregates: function(req, res) {
		var releases = null;
		//pieChart by release
		var pieCharts = [];
		var pieChartLastBuild = [];
		//get all releases
		Release.getReleases(function(results) {releases = results});

		releases.forEach(function(release) {
			// var passCount = 0;
			// var failCount = 0;
			// var skipCount = 0;
			// var unknownCount = 0;
			// var reports = null;
			var pieChartData = [];
			var pieChartLastBuildData = [];
			var lastBuild = null;
			Build.getLastBuildByRelease(release.id, function(build){
				lastBuild = build;
			});
			Report.getPieChartData({autoGenerated: true, build: lastBuild.id}, function(data){
				pieChartLastBuildData = data;
			});
			// Report.getReports(,function(result) {
			// 	reports = result;
			// });
			Report.getPieChartData({autoGenerated: true, release: release.id}, function(data){
				pieChartData = data;
			});
			// _(reports).forEach(function(report){
			// 	passCount += report.passTests;
			// 	failCount += report.failTests;
			// 	skipCount += report.skipTests;
			// 	unknownCount += report.unknownTests;
			// });
			// var pieChartData = {
			// 	{name : 'pass',
			// 	count: passCount},
			// 	{name : 'fail',
			// 	count: failCount},
			// 	{name : 'skip',
			// 	count: skipCount},
			// 	{name : 'unknown',
			// 	count: unknownCount}
			// };
			var piechart = {
				name : release.name,
				data : pieChartData
			};
			var piechartLastBuild = {
				release : release.name,
				name : lastBuild.name,
				data : pieChartLastBuildData
			};
			pieCharts.push(piechart);
			pieChartLastBuild.push(piechartLastBuild);
		});

        var view = function() {
            var out = {
                releases: releases,
                pieCharts: pieCharts,
                pieChartLastBuild: pieChartLastBuild
            };
            
            res.json(out);
        }

		//return json output
		view();

	},


	/*
	BML status example with existing db
	*/
	bmlPieData: function(req,res) {

		var buildName = '5.0.0.28';
		DbGetterController.getBmlPieData(buildName,'BML',function(result)
		{
            var out = {
                buildName: buildName,
                pieChartData: result
            };
            
            res.send(out);
		});
	}

};

