/**
 * Report.js
 *
 * @description :: TODO: You might write a short summary of how this model works and what it represents here.
 * @docs        :: http://sailsjs.org/documentation/concepts/models-and-orm/models
 */

module.exports = {

  attributes: {
    /*
    one-to-many
    */
    release: {
      model: 'release'
    },
  	/*
  	one-to-many
  	*/
  	build: {
  		model: 'Build'
  	},
  	/*
  	one-to-many
  	*/
  	run: {
  		model: 'Run'
  	},
  	/*
  	one-to-many
  	*/
  	tests: {
  		collection: 'TestCase',
  		via: 'report'
  	},
  	/*
  	one-to-many
  	*/
  	projects: {
  		collection: 'Project',
  		via: 'report'
  	},
  	startTime: 'datetime',
    endTime: 'datetime',

    passTests: 'number',
    failTests: 'number',
    skipTests: 'number',
    unknownTests: 'number',
    autoGenerated: 'boolean'  //tag determin whether this report is auto generated or not for a run.
  },

  getReport: function(id, cb) {
    Report.findOne({
        id: id
    }).exec(function(err, result) {
        if (err) console.log('ReportService.getReport -> ' + err);
        
        cb(result);
    });
  },

  getReports: function(json, cb) {
    Report.find(json).exec(function(err, result) {
        if (err) console.log('ReportService.getReports -> ' + err);
        
        cb(result);
    });
  },

  getPieChartDataByReports: function(json,cb) {
      var passCount = 0;
      var failCount = 0;
      var skipCount = 0;
      var unknownCount = 0;
      Report.getReports(json,function(reports){
      
      reports.forEach(function(report){
        passCount += report.passTests;
        failCount += report.failTests;
        skipCount += report.skipTests;
        unknownCount += report.unknownTests;
      });

      var pieChartData = [
        {name : 'pass',
        count: passCount},
        {name : 'fail',
        count: failCount},
        {name : 'skip',
        count: skipCount},
        {name : 'unknown',
        count: unknownCount}
      ];

      cb(pieChartData);
    });
  }

  // getReportsByBuild: function(id, cb) {
  // Report.find({build: id}).exec(function(err, result){
  //   if(err) console.log(err);
  //   else {
  //     cb(result);
  //     }
  //   });
  // }

};

