/**
 * Report.js
 *
 * @description :: TODO: You might write a short summary of how this model works and what it represents here.
 * @docs        :: http://sailsjs.org/documentation/concepts/models-and-orm/models
 */

module.exports = {

  attributes: {
    /*
    one-to-many
    */
    release: {
      model: 'release'
    },
  	/*
  	one-to-many
  	*/
  	build: {
  		model: 'Build'
  	},
  	/*
  	one-to-many
  	*/
  	run: {
  		model: 'Run'
  	},
  	/*
  	one-to-many
  	*/
  	tests: {
  		collection: 'TestCase',
  		via: 'report'
  	},
  	/*
  	one-to-many
  	*/
  	projects: {
  		collection: 'Project',
  		via: 'report'
  	},
  	startTime: 'datetime',
    endTime: 'datetime',

    passTests: 'number',
    failTests: 'number',
    skipTests: 'number',
    unknownTests: 'number',
    autoGenerated: 'boolean'  //tag determin whether this report is auto generated or not for a run.
  },

  getReport: function(id, cb) {
    Report.findOne({
        id: id
    }).exec(function(err, result) {
        if (err) console.log('ReportService.getReport -> ' + err);
        
        cb(result);
    });
  },

  

};

